###################
### NUTTX BUILD ###
###################
ifneq ($(APPDIR),)
include nuttx.mk
#############################
### REGULAR DESKTOP BUILD ###
#############################
else
include desktop.mk
endif
